export { default as About } from './About'
export { default as Contact } from './Contact'
export { default as Content } from './Content'
export { default as Footer } from './Footer'
export { default as Head } from './Head'
export { default as Media } from './Media'
export { default as Nav } from './Nav'
export { default as Title } from './Title'
